service: defaultlp

image: sdoering/vdefaul-lp

servers:
  web:
    - 116.203.36.121

proxy:
  ssl: true
  hosts:
    - ein-mensch.net
    - moorbekstrasse.de
    - moorbekstraße.de
    - xn--moorbekstrae-v9a.de
  app_port: 5003

registry:
  server: ghcr.io
  username:
    - DOCKER_REGISTRY_TOKEN
  password:
    - DOCKER_REGISTRY_TOKEN

builder:
  arch: amd64